prometheus-server:
  image: prom/prometheus
  ports:
    - 9090:9090
  links:
    - node_exporter:node_exporter
  volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

grafana-ui:
  image: grafana/grafana
  ports:
    - 3000:3000
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
  links:
    - prometheus-server:prometheus

node_exporter:
  image: quay.io/prometheus/node-exporter:latest
  ports:
    - 9100:9100
  command:
    - '--path.rootfs=/host'
  volumes:
    - '/:/host:ro,rslave'
